apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-database
  labels:
    app: postgresql-database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path