apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypv
spec:
  selector:
    matchLabels:
      app: mypv
  template:
    metadata:
      labels:
        app: mypv
    spec:
      volumes:
        - name: webdata
          persistentVolumeClaim: 
            claimName: mypvc
      containers:
      - name: mypv
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webdata
          mountPath: /usr/share/nginx/html