apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    app: mypv-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/mypv"
    type: DirectoryOrCreate