apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-database-pvc-new
  labels:
    app: mysql-database-secret-es
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
